### ISSUE TITLE
function contrastive_loss  loss

### ISSUE THREAD

**Issue by docterbio** [ys-zong/conST#1]
Hi Author!
       I met some errors when running conST, which reported the error "did not define the function contrastive_loss".   I didn't find the code of contrastive_loss in the model.py or in the training.py. Could you help me solve it?

  Thanks!

**Comment by ys-zong** [comment]
Hi,

Thanks for your interest. I guess you are referring [here](https://github.com/ys-zong/conST/blob/e0896ab3ce6293a4bf50bcde0b019aa0654d9cac/src/training.py#L247). That is a typo and I've fixed it. It is the local-to-local contrastive loss. Sorry for the confusion.
