### ISSUE TITLE
Hello, can you confirm that the torchvision version is indeed 0.9.2?

### ISSUE THREAD

**Issue by 0225yyyyyqq** [ys-zong/conST#6]
Hello, can you confirm that the torchvision version is indeed 0.9.2?

**Comment by ys-zong** [comment]
Sorry for the very late reply. Yes, I used Torchvision 0.9.2.

**Comment by 0225yyyyyqq** [comment]
Thanks so much
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Yongshuo ***@***.***>
            
        
      
      
        
         Date 
        
        
        2/16/2024 14:21
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [ys-zong/conST] Hello, can you confirm that the torchvision version is indeed 0.9.2? (Issue #6)
        
      
    
  

Sorry for the very late reply. Yes, I used Torchvision 0.9.2.
